### ISSUE TITLE
[BUG] Deprecated package 

### ISSUE THREAD

**Issue by Judge-Paul** [Dun-sin/template-portfolio#14]
### Description

The `"emailjs-com"` package used in this project has been deprecated and the package to be used is `"@emailjs/browser"`

The code in the [Mail.jsx file](https://github.com/Dun-sin/template-portfolio/blob/main/src/Components/Mail.jsx#L55-L60) can be updated like this using the new package

Old Code
``` javascript
import { send } from 'emailjs-com';

send(serviceID, templateID, {
  subject: toSend.subject,
  name: toSend.name,
  email: toSend.email,
  message: toSend.message,
}, publicKey);
```
New Code 
``` javascript
import emailjs from '@emailjs/browser';

emailjs.send(serviceID, templateID, toSend, publicKey)
  .then((response) => {
	   console.log('SUCCESS!', response.status, response.text);
  }, (err) => {
	   console.log('FAILED...', err);
});
```
**Note:** _The code above hasn't been tested in the codebase._ 

You can also use `react-toastify` to display success or failed to the user.

### Screenshots

![image](https://github.com/Dun-sin/template-portfolio/assets/110723341/7e5862e3-a75d-4089-806c-2b4952698a8e)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/template-portfolio/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Judge-Paul** [comment]
@Dun-sin are you always active on github 😲?

**Comment by Dun-sin** [comment]
> @Dun-sin are you always active on github 😲?

No, notifications

**Comment by Judge-Paul** [comment]
@Dun-sin just made a PR
