### ISSUE TITLE
[DOCS] add readme file

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/template-portfolio#2]
### Description

Add a readme file, it should have:
— what the project is about
— technologies used (they are: react, email.js)
— how to install & run

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/template-portfolio/blob/main/CONTRIBUTING.md)

**Comment by udaykahar** [comment]
i'll do that

**Comment by abhishekr700** [comment]
Hi @Dun-sin, Please assign this to me.
